#ifndef ERROR_CODES_H
#define ERROR_CODES_H

enum ErrorCode
{
    SUCCESS = 0,
    ERROR_FILE_NOT_FOUND,
    ERROR_INVALID_FORMAT,
    ERROR_WRITE_FAILED,
    ERROR_READ_FAILED,
    ERROR_OUT_OF_MEMORY,
    ERROR_UNKNOWN
};

#endif // ERROR_CODES_H
