name: Build and Release

on:
  push:
    branches:
        - 'develop'
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: windows-l
    permissions:
      contents: write
      packages: write # Required to push cache to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
