name: Build and Release

on:
  push:
    branches:
        - 'develop'
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write # Required to push cache to GHCR
      actions: write

    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v4

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
            # Use the compatible driver for the Windows runner
            driver: docker

      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry:  docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
  
      - 
        name: Build image and export artifact
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build.Dockerfile
          github-token: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          platforms: windows/amd64
          # This tells the action to copy the final build output to a local directory
          outputs: type=local,dest=./Output
          # This enables caching using the GitHub Actions cache backend.
          cache-from: type=registry,ref=ghcr.io/tkasozi/win-vcpkg-mingw64-qt-cpp-minimal:cache
          cache-to: type=registry,ref=ghcr.io/tkasozi/win-vcpkg-mingw64-qt-cpp-minimal:cache,mode=max

      - 
        name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - 
        name: Upload Release Asset (setup.exe)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Output/setup.exe
          asset_name: setup.exe
          asset_content_type: application/octet-stream