name: Delete Older Releases

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  delete-older-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Delete older releases
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 2
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}