name: win-vcpkg-mingw64-qt-cpp-minimal CI

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'vcpkg.json'
      - 'base_image/win/Dockerfile'
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'vcpkg.json'
      - 'base_image/win/Dockerfile'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: win-vcpkg-mingw64-qt-cpp-minimal

jobs:
  build-and-push:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.description="Windows Vcpkg MinGW64 Qt C++ Minimal Docker Image"
            org.opencontainers.image.version=latest
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./base_image/win/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

