# .github/workflows/callable-build-logic.yml
name: Reusable Build Logic

env:
  CI: True
  DOTNET_SDK_VERSION: 9.0.303
  DOTNET_VERSION: 9.0.7
  CMAKE_EXE: "cmake"

# This workflow can be called by other workflows
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
        description: 'Runner operating system'
      build_type:
        required: true
        type: string
        description: 'Build configuration (Debug/Release)'
      vcpkg_triplet:
        required: false
        type: string
        description: 'Vcpkg triplet for the target platform'
      generator:
        required: false
        type: string
        description: 'Build generator'
      arch:
        required: true
        type: string
        description: 'Supported Arch'
      system:
        required: true
        type: string
        description: 'System build plus arch'

    secrets:
      GH_PACKAGES_TOKEN:
        required: true
        description: 'GitHub Packages PAT'


jobs:
  build_component:
    runs-on: ${{ inputs.os }}
    env:
      PROJECT_NAME: buraq
      APP_EXE_NAME: "buraq-${{ inputs.system }}-${{ github.event.release.tag_name || 'x.x.x-dev' }}"
      APP_VERSION: ${{ github.event.release.tag_name || 'x.x.x-dev' }} # Assuming your release tag follows a versioning scheme
      OUTPUT_DIR: ${{ github.workspace }}\buraq\Output
      APP_BINARY: ${{ github.workspace }}\buraq\build\build

    outputs:
      build_successful: ${{ steps.build_project_step.outcome == 'success' }}
      executable_name: ${{ env.APP_EXE_NAME }}

    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          path: ${{ env.PROJECT_NAME }}
          fetch-depth: 0

      - name: Clone Vcpkg Repository
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          ref: master
          path: vcpkg
          fetch-depth: 0

      - name: Set up MSYS2 with Build Tools
        if: inputs.vcpkg_triplet == 'x64-mingw-dynamic' # Only run if MinGW is used
        uses: msys2/setup-msys2@v2
        id: msys2-setup
        with:
          update: true
          install: >
            mingw-w64-x86_64-toolchain
            git
          path-type: minimal
          msystem: MINGW64

      - name: Setup .NET SDK ${{ env.DOTNET_SDK_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Build Managed project
        id: dotnet-project
        working-directory: ${{ github.workspace }}/${{ env.PROJECT_NAME }}
        run: |
          ls -alh

          cd CSharpManaged

          ./build.sh

        shell: bash

      - name: Bootstrap Vcpkg
        working-directory: ${{ github.workspace }}/vcpkg
        run: git pull origin master; ./bootstrap-vcpkg.bat
        shell: msys2 {0}

      - name: Configure NuGet for GitHub Packages
        shell: pwsh
        env:
          USERNAME: ${{ github.repository_owner }}
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
        run: |
          $nugetConfigPath = Join-Path $env:APPDATA "NuGet\NuGet.Config"
          $nugetConfigContent = @"
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <packageSources>
              <clear />
              <add key="GitHubPackages" value="https://nuget.pkg.github.com/$env:USERNAME/index.json" />
            </packageSources>
            <packageSourceCredentials>
              <GitHubPackages>
                <add key="Username" value="$env:USERNAME" />
                <add key="ClearTextPassword" value="$env:GH_PACKAGES_TOKEN" />
              </GitHubPackages>
            </packageSourceCredentials>
          </configuration>
          "@
          New-Item -ItemType Directory -Force -Path (Split-Path $nugetConfigPath)
          $nugetConfigContent | Out-File $nugetConfigPath
          Write-Host "Created NuGet.Config at $nugetConfigPath"

      - name: Set NuGet API Key for GitHub Packages
        shell: pwsh
        env:
          VCPKG_EXE: ${{ github.workspace }}/vcpkg/vcpkg.exe
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
        run: |
          $nuget_path = & "${{ env.VCPKG_EXE }}" fetch nuget | Select-String -Pattern '\S+\.exe$' | ForEach-Object { $_.Matches[0].Value }
          if (-not $nuget_path) { Write-Error "Failed to get nuget.exe path."; exit 1 }
          & "$nuget_path" setapikey "${{ env.GH_PACKAGES_TOKEN }}" -Source "GitHubPackages" -NonInteractive 2>&1 | Write-Host

          Write-Host "API Key for GitHubPackages set successfully."

      - name: Cache Vcpkg Asset Downloads
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/vcpkg/downloads
            ${{ github.workspace }}/vcpkg/toolsrc
          key: ${{ inputs.os }}-${{ inputs.build_type }}-${{ inputs.vcpkg_triplet }}-vcpkg-assets-${{ hashFiles('buraq/vcpkg.json') }}
          restore-keys: |
            ${{ inputs.os }}-${{ inputs.vcpkg_triplet }}-vcpkg-assets-

      - name: Configure CMake and Install Vcpkg Dependencies
        id: set-cmake-path
        working-directory: ${{ github.workspace }}/${{ env.PROJECT_NAME }}
        env:
          VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json,readwrite"
          VCPKG_INSTALL_OPTIONS: "--debug"
          VCPKG_NUGET_ACCESSTOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
          CMAKE_DOTNET_TARGET_FRAMEWORK: ${{ env.DOTNET_ROOT }}/packs/Microsoft.NETCore.App.Host.win-x64/${{ env.DOTNET_VERSION }}/runtimes/win-x64/native
          VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
          VCPKG_DEFAULT_HOST_TRIPLET: ${{ inputs.vcpkg_triplet }}
          VCPKG_EXE: ${{ github.workspace }}/vcpkg/vcpkg.exe
        shell: msys2 {0}
        run: |
          # "${{ env.VCPKG_EXE }}" install
          
          # ls -alh "${{ env.VCPKG_ROOT }}/downloads/tools"
          
          VCPKG_CMAKE_PATH="$("${{ env.VCPKG_EXE }}" fetch cmake | tail -n 1)"
    
          echo "Found Vcpkg CMake executable at: $VCPKG_CMAKE_PATH"
          
          echo "vcpkg-cmake-path=$VCPKG_CMAKE_PATH" >> $GITHUB_OUTPUT
          
          "$VCPKG_CMAKE_PATH" -B build \
               -S . \
               -G "Ninja" \
               -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" \
               -DVCPKG_TARGET_TRIPLET="${{ inputs.vcpkg_triplet }}" \
               -DVCPKG_DEFAULT_HOST_TRIPLET="${{ inputs.vcpkg_triplet }}" \
               -DCMAKE_BUILD_TYPE="${{ inputs.build_type }}" \
               -DCMAKE_DOTNET_TARGET_FRAMEWORK="${CMAKE_DOTNET_TARGET_FRAMEWORK}" \
               -DCMAKE_MAKE_PROGRAM="${{ env.VCPKG_ROOT }}/downloads/tools/ninja/1.12.1-windows/ninja.exe"

      - name: Build Project
        if: inputs.vcpkg_triplet == 'x64-mingw-dynamic' && success()
        working-directory: ${{ github.workspace }}/${{ env.PROJECT_NAME }}/build
        run: |
          VCPKG_CMAKE_PATH="${{ steps.set-cmake-path.outputs.vcpkg-cmake-path }}"
          "$VCPKG_CMAKE_PATH" --build . --config ${{ inputs.build_type }}
        shell: msys2 {0}

      - name: Download Inno Setup
        run: |
          Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe?site=1" -OutFile "inno_setup.exe"
          Start-Process -Wait -FilePath "inno_setup.exe" -ArgumentList "/SILENT"
        shell: powershell

      - name: Generate installer with Inno Setup
        run: |
          Get-ChildItem -Path "${{ env.APP_BINARY }}" -Filter "${{ env.PROJECT_NAME }}.exe" | Select-Object -First 1 -ExpandProperty Name | Out-File -FilePath app_exe_name.txt
          
          $exeName = Get-Content -Path "app_exe_name.txt"
          $appName = $exeName.Replace(".exe", "")
          
          Write-Host "APP_NAME set to $appName"
          
          $innoSetupExe = "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
          $innoScriptPath = "${{ github.workspace }}/${{ env.PROJECT_NAME }}/buraq.iss"
          
          $appExeName = "$(cat app_exe_name.txt)"
          $appVersion = "${{ env.APP_VERSION }}"
          $outputDirForInno = "${{ env.OUTPUT_DIR }}"
          $appBinaryDir = "${{ env.APP_BINARY }}"
          $appArchSupport = "${{ inputs.arch }}compatible"
          $appOutputBaseFilename = "setup-${{ env.APP_EXE_NAME }}"
          
          & "$innoSetupExe" "$innoScriptPath" `
            "/DAppName=$appName" `
            "/DAppExeName=$appExeName" `
            "/DAppVersion=$appVersion" `
            "/DOutputDir=$outputDirForInno" `
            "/DAppBinaryDir=$appBinaryDir" `
            "/DAppArchSupport=$appArchSupport" `
            "/DAppOutputBaseFilename=$appOutputBaseFilename"

        shell: powershell

      - name: Show Created files after build
        run: ls -al .; echo "*****************************\n\n"; ls -al "${{ github.workspace }}\${{ env.PROJECT_NAME }}"; ls -al "${{ github.workspace }}\${{ env.PROJECT_NAME }}\Output"; echo "**** OUTPUT_DIR:${{ env.OUTPUT_DIR }}***"
        shell: bash

      - name: Create release archive
        uses: thedoctor0/zip-release@master
        with:
          filename: ${{ inputs.system }}-${{ inputs.build_type }}-build-artifacts.zip
          directory: ${{ env.OUTPUT_DIR }}

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.system }}-${{ inputs.build_type }}-build-artifacts
          path: ${{ env.OUTPUT_DIR }}\setup-${{ env.APP_EXE_NAME }}.exe
          retention-days: 1

