name: test-build.yml

on:
  push:
    branches:
      - '**'        # Matches all branches
      - '!main'     # Excludes the 'main' branch

  pull_request:
    branches:
      - 'develop'

jobs:
  # This job triggers the reusable workflow for each matrix combination
  build_and_package:
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        #        os: [ windows-latest, ubuntu-latest, macos-latest ]
        build_type: [ Release ]
        include:
          - os: windows-latest
            vcpkg_triplet: x64-mingw-dynamic
            generator: "Ninja"
            arch: x64
    #          - os: ubuntu-latest
    #            vcpkg_triplet: x64-linux
    #          - os: macos-latest
    #            vcpkg_triplet: x64-osx

    uses: ./.github/workflows/reusable-build.yml # Calls the reusable workflow

    secrets:
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
    with:
      os: ${{ matrix.os }}
      build_type: ${{ matrix.build_type }}
      vcpkg_triplet: ${{ matrix.vcpkg_triplet }}
      generator: ${{ matrix.generator }}
      arch: ${{ matrix.arch }}

