name: test-build.yml

on: [ push, pull_request ]

jobs:
  # This job triggers the reusable workflow for each matrix combination
  build_and_package:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        build_type: [ Release ]
        include:
          - os: windows-latest
            vcpkg_triplet: x64-windows
            generator: "Visual Studio 17 2022"
            arch: x64
          - os: ubuntu-latest
            vcpkg_triplet: x64-linux
          - os: macos-latest
            vcpkg_triplet: x64-osx

    uses: ./.github/workflows/reusable-build.yml # Calls the reusable workflow
    secrets:
      # Pass the secret from the caller workflow to the reusable workflow
      gh_packages_token: ${{ secrets.GH_PACKAGES_TOKEN }}
    with:
      os: ${{ matrix.os }}
      build_type: ${{ matrix.build_type }}
      vcpkg_triplet: ${{ matrix.vcpkg_triplet }}
      gh_packages_token: ${{ secrets.gh_packages_token }}

