name: Validate Merge Branch

on:
  pull_request:
    branches:
      - main

jobs:
  check_source_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}"
          REQUIRED_SOURCE_BRANCH="develop" # <--- IMPORTANT: Replace with your actual allowed branch name

          if [[ "$SOURCE_BRANCH" != "$REQUIRED_SOURCE_BRANCH" ]]; then
            echo "Error: Only the '$REQUIRED_SOURCE_BRANCH' branch can merge into 'main'."
            echo "This pull request is from '$SOURCE_BRANCH'."
            exit 1
          else
            echo "Source branch '$SOURCE_BRANCH' is allowed to merge into 'main'."
          fi